### ISSUE TITLE
Make result setter as a centralized Oracle

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-core#25]

**Comment by chrisli30** [comment]
@dwalintukan I've put this in P2 for now. Let me know if you want to adjust its priority.

**Comment by chrisli30** [comment]
Discussed with Xiahong, he means to extract CentralizedOracle as a class in contract like gnosis did, to separate the concept from voting oracle. What do you think @dwalintukan?

https://github.com/gnosis/gnosis-contracts/blob/master/contracts/Oracles/CentralizedOracle.sol

**Comment by dwalintukan** [comment]
@chrisli30 I like the idea. I will abstract Centralized and Voting Oracles to their own classes then. P2 is ok.
