### ISSUE TITLE
clean event to monitor the state of topicEvent, oracleEvent & resultsetter from application

### ISSUE THREAD

**Issue by frankhu-optimizely** [bodhiproject/bodhi-core#42]
All Events needed:

topicEventCreated(...)
voteEventCreated(...)
bettingOnEvent(betterAddr, eventAddr, resultIdx, amout)
resultSetOnEvent(...)
finalResultSetOnTopic(...)

**Comment by dwalintukan** [comment]
**EventFactory**
event topicCreated(...)

**TopicEvent**
event bettingOnEvent(betterAddr, eventAddr, resultIdx, amout)
event finalResultSetOnTopic(...)

**OracleFactory**
event OracleCreated(topicEventAddr, etc...)

**Oracle**
event voteResult()
event oracleResultSet()
